require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-hc
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Max: 35
  Exclude:
    - 'db/migrate/*'
Metrics/AbcSize:
  Max: 50
  Exclude:
    - 'db/migrate/*'
Metrics/BlockLength:
  Exclude:
    - config/environments/*.rb
    - config/routes.rb
Layout/LineLength:
  Exclude:
    - config/initializers/devise.rb
    - db/migrate/*.rb
Hc/RailsSpecificActionName:
  Exclude:
    - app/controllers/users/omniauth_callbacks_controller.rb
    - app/controllers/tweets_controller.rb
RSpec/MultipleExpectations:
  Enabled: false
RSpec/ContextWording:
  Enabled: false
RSpec/ExampleLength:
  Max: 15